# Generated by Django 3.2.2 on 2021-05-20 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0002_order_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='item',
            field=models.ForeignKey(db_column='medicine_name', on_delete=django.db.models.deletion.CASCADE, to='pharma.medicinedetails'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, db_column='medicine_name', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharma.medicinedetails'),
        ),
    ]
